# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "lenovo-legion-module" ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelParams = [ 
    # fix: can't go 120hz+
    "nvidia-modeset.hdmi_deepcolor=0" 
    # fix: screen flickering when on iGPU
    "i915.enable_psr=0"
  ]; 

  # fix: hivernation issues NVIDIA
  boot.extraModprobeConfig = ''
    options nvidia_modeset vblank_sem_control=0
  '';
  boot.extraModulePackages = with config.boot.kernelPackages; [ lenovo-legion-module ];
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/179ad3a0-940b-419b-bed1-9ab772380ce0";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4033-D53F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
  fileSystems."/media/kozue" =
    { device = "/dev/disk/by-uuid/8C9E886D9E88519E";
      fsType = "ntfs3";
      options = [ "rw" "uid=1000" "nofail" ];
    };
  fileSystems."/media/windows" =
    { device = "/dev/disk/by-uuid/982834552834351A";
      fsType = "ntfs3";
      options = [ "ro" "uid=1000" "nofail" ];
    };
  
  swapDevices = [{
    device = "/swapfile";
    size = 12 * 1024; # 12GB
  }];
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp9s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
